name: location_tracker
description: it track user location information and share it with the team.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.6
  location: ^4.4.0
  cloud_firestore: ^3.1.17
  firebase_core: ^1.17.1
  permission_handler: ^9.2.0
  fluttertoast: ^8.0.9
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  rolling_switch: ^0.0.2
  flutter_background: ^1.1.0
  http: ^0.13.5
  device_preview: ^1.1.0
  sizer: ^2.0.15
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_launcher.png"

 
  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

 

 
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
